FROM php:8.2-fpm

WORKDIR /var/www/

RUN apt-get update && apt-get install -y \ 
    git \ 
    curl \ 
    zip \ 
    unzip
    
COPY ./composer.json ./

RUN apt-get update && apt-get install -y libpq-dev && docker-php-ext-install pdo pdo_pgsql

RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

ENV  COMPOSER_ALLOW_SUPERUSER=1

RUN composer install 

